version: '3'
services:
  account-service:
    image: account-service
    container_name: account-service
    ports:
      - "8080:8080"
    networks:
      - system-test_dtupay-network

networks:
  system-test_dtupay-network:
    external: true